### ISSUE TITLE
Unstable SP/HB lockout  **bug**

### ISSUE THREAD

**Issue by shananas** [WaterKH/ReWrite#72]
Using the unstable branch after cube minigame in SP it activated the story cutscene going back to HB to learn about the DTD and removed HB and the SP portal took me to data larxene.
https://www.twitch.tv/videos/944466375

**Comment by WaterKH** [comment]
After reviewing the footage, I believe you may have a modified ISO, which may have some weird bugs that I cannot control.

I have tested with CrazyKatPatch along with the GOA mod as well as just the GOA mod. Anything beyond this may have some weird things happen.

Although, Bio-Roxas was also able to break the game and fight Data Xemnas too, so it must be some kind of thing with modified ISOs that have the potential to break, or it could be an overflow issue as well.

**Comment by shananas** [comment]
Yes I have mario instead of mickey and naxshe's HDification patch so that makes sense. Something that I think shouldnt be affected is the change room doesn't always send me to the correct room.
